<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;

/** @var \Joomla\Component\Content\Site\View\Category\HtmlView $this */
// Create a shortcut for params.
$params = $this->item->params;
$attribs = json_decode($this->item->attribs ?? "");
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);
$article_format = (isset($attribs->helix_ultimate_article_format) && $attribs->helix_ultimate_article_format) ? $attribs->helix_ultimate_article_format : 'standard';

$template = HelixUltimate\Framework\Platform\Helper::loadTemplateData();
$tmpl_params = $template->params;

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate   = Factory::getDate()->format('Y-m-d H:i:s');
$isUnpublished = ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED || $this->item->publish_up > $currentDate)
    || ($this->item->publish_down < $currentDate && $this->item->publish_down !== null);

$content_center = $tmpl_params->get('blog_center_content');

$content_margin = $tmpl_params->get('leading_blog_list_content_margin', 'default');
$content_margin_cls = $content_margin == 'default' ? 'uk-margin-top' : 'uk-margin-'.$content_margin.'-top';
$content_margin_cls .= $content_center ? ' uk-text-center' : '';

$content_length = $tmpl_params->get('content_length');

$image_margin = $tmpl_params->get('image_margin', 'default');
$image_margin_cls = $image_margin == 'default' ? ' uk-margin-top' : ' uk-margin-'.$image_margin.'-top';
$blog_tag_cls = $content_center ? ' class="uk-text-center"' : '';
$mediaOutput = '';

switch($article_format) {
	case 'gallery':
		$mediaOutput = LayoutHelper::render('joomla.content.blog.gallery', array('attribs' => $attribs, 'id' => $this->item->id));
		break;
	
	case 'video':
		$mediaOutput = LayoutHelper::render('joomla.content.blog.video', array('attribs' => $attribs));
		break;
	
	case 'audio':
		$mediaOutput = LayoutHelper::render('joomla.content.blog.audio', array('attribs' => $attribs));
		break;
	
	default:
		$mediaOutput = LayoutHelper::render('joomla.content.intro_image', $this->item);
		break;
}
?>

	<?php if (!empty($mediaOutput)) : ?>
		<div class="uk-text-center<?php echo $image_margin_cls; ?>">
			<?php echo $mediaOutput; ?>
		</div>
	<?php endif; ?>

    <?php if ($isUnpublished) : ?>
        <div class="system-unpublished">
    <?php endif; ?>

    <?php // Todo Not that elegant would be nice to group the params ?>
	<?php if ($info == 0) : ?>
		<?php echo LayoutHelper::render('joomla.content.meta_block', $this->item); ?>
	<?php endif; ?>

    <?php echo LayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item); ?>

	<?php if ($info != 0) : ?>
		<?php echo LayoutHelper::render('joomla.content.meta_block', $this->item); ?>
	<?php endif; ?>

    <?php if (!$params->get('show_intro')) : ?>
        <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
        <?php echo $this->item->event->afterDisplayTitle; ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

	<div class="<?php echo $content_margin_cls; ?>" property="text">
        <?php if (is_numeric($content_length) && $content_length >= 0) : ?>
            <?php echo substr(strip_tags($this->item->introtext), 0, $content_length) . '...'; ?>
        <?php else : ?>
            <?php echo $this->item->introtext; ?>
        <?php endif ?> 
	</div>

    <?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
        <p<?php echo $blog_tag_cls; ?>><?php echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?></p>
    <?php endif; ?>

    <?php if ($params->get('show_readmore') && $this->item->readmore) :
        if ($params->get('access-view')) :
            $link = Route::_(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
        else :
            $menu = Factory::getApplication()->getMenu();
            $active = $menu->getActive();
            $itemId = $active->id;
            $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
            $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
        endif; ?>

        <?php echo LayoutHelper::render('joomla.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>

    <?php endif; ?>

	<?php // Language Associations ?>
	<?php if ($assocParam && !empty($this->item->associations)) : ?>
		<div class="uk-article-associations uk-margin-top">
			<div class="uk-flex uk-flex-middle uk-flex-wrap">
				<span class="uk-margin-small-right">
					<span class="icon-globe icon-fw" aria-hidden="true"></span>
					<?php echo Text::_('JASSOCIATIONS'); ?>
				</span>
				
				<ul class="uk-iconnav">
					<?php foreach ($this->item->associations as $association) : ?>
						<li>
							<?php if ($params->get('flags', 1) && !empty($association['language']->image)) : ?>
								<?php 
								$flag = HTMLHelper::_('image', 
									'mod_languages/' . $association['language']->image . '.gif', 
									htmlspecialchars($association['language']->title_native, ENT_QUOTES, 'UTF-8'),
									['title' => htmlspecialchars($association['language']->title_native, ENT_QUOTES, 'UTF-8')], 
									true
								);
								?>
								<a href="<?php echo Route::_($association['item']); ?>" 
									title="<?php echo htmlspecialchars($association['language']->title_native, ENT_QUOTES, 'UTF-8'); ?>">
									<?php echo $flag; ?>
								</a>
							<?php else : ?>
								<a href="<?php echo Route::_($association['item']); ?>" 
									class="uk-button uk-button-small uk-button-default" 
									title="<?php echo htmlspecialchars($association['language']->title_native, ENT_QUOTES, 'UTF-8'); ?>">
									<?php echo strtoupper($association['language']->lang_code); ?>
									<span class="visually-hidden"><?php echo htmlspecialchars($association['language']->title_native, ENT_QUOTES, 'UTF-8'); ?></span>
								</a>
							<?php endif; ?>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	<?php endif; ?>

	<?php if (($params->get('show_parent_category') && !empty($this->item->parent_id)) || $params->get('show_create_date') || $params->get('show_modify_date') || $params->get('show_hits')) : ?>
		<ul class="uk-list uk-article-meta-list">
			<?php if ($params->get('show_parent_category') && !empty($this->item->parent_id)) : ?>
				<li>
					<?php 
					$parentCategory = !empty($this->item->parent_title) ? htmlspecialchars($this->item->parent_title, ENT_QUOTES, 'UTF-8') : 'Parent Category'; 
					?>
					<?php echo LayoutHelper::render('joomla.icon.iconclass', ['icon' => 'icon-folder icon-fw']); ?>
					<?php if ($params->get('link_parent_category')) : ?>
						<?php $parentCategoryUrl = Route::_(RouteHelper::getCategoryRoute($this->item->parent_id, $this->item->language ?? null)); ?>
						<?php echo Text::sprintf('COM_CONTENT_PARENT', HTMLHelper::_('link', $parentCategoryUrl, $parentCategory)); ?>
					<?php else : ?>
						<?php echo Text::sprintf('COM_CONTENT_PARENT', $parentCategory); ?>
					<?php endif; ?>
				</li>
			<?php endif; ?>

			<?php if ($params->get('show_create_date') && !empty($this->item->created)) : ?>
				<li>
					<span class="icon-calendar icon-fw" aria-hidden="true"></span>
					<time datetime="<?php echo HTMLHelper::_('date', $this->item->created, 'c'); ?>" itemprop="dateCreated">
						<?php echo Text::sprintf('TPL_META_DATE_CREATED', HTMLHelper::_('date', $this->item->created, Text::_('DATE_FORMAT_LC3'))); ?>
					</time>
				</li>
			<?php endif; ?>

			<?php if ($params->get('show_modify_date') && !empty($this->item->modified)) : ?>
				<li>
					<span class="icon-calendar icon-fw" aria-hidden="true"></span>
					<time datetime="<?php echo HTMLHelper::_('date', $this->item->modified, 'c'); ?>" itemprop="dateModified">
						<?php echo Text::sprintf('TPL_META_DATE_MODIFIED', HTMLHelper::_('date', $this->item->modified, Text::_('DATE_FORMAT_LC3'))); ?>
					</time>
				</li>
			<?php endif; ?>

			<?php if ($params->get('show_hits') && !empty($this->item->hits)) : ?>
				<li>
					<span class="icon-eye icon-fw" aria-hidden="true"></span>
					<meta content="UserPageVisits:<?php echo (int)$this->item->hits; ?>" itemprop="interactionCount">
					<?php echo Text::sprintf('COM_CONTENT_ARTICLE_HITS', number_format((int)$this->item->hits)); ?>
				</li>
			<?php endif; ?>
		</ul>
	<?php endif; ?>

    <?php if ($canEdit) : ?>
        <?php echo LayoutHelper::render('joomla.content.icons', ['params' => $params, 'item' => $this->item]); ?>
    <?php endif; ?>

    <?php if ($isUnpublished) : ?>
        </div>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
    <?php echo $this->item->event->afterDisplayContent; ?>
